# Generated by Django 4.1.4 on 2023-02-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
    ]
