# Generated by Django 4.1.4 on 2023-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('A', 'Amazon'), ('M', 'Mint'), ('C', 'Chase'), ('F', 'Fidelity')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
