# Generated by Django 4.1.4 on 2023-02-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0002_account_id_category_id_alter_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(choices=[('U', 'Uncategorized'), ('C', 'Categorized')], default='U', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Seeded',
        ),
    ]
