# Generated by Django 3.2.8 on 2021-11-16 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0003_alter_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='phrase_match',
            new_name='predicate',
        ),
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
