# Generated by Django 4.1.4 on 2023-02-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0003_seedrequest_delete_seeded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedrequest',
            name='seed_type',
        ),
        migrations.AddField(
            model_name='seedrequest',
            name='categories_filename',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedrequest',
            name='descriptions_filename',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedrequest',
            name='transactions_filename',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
