# Generated by Django 4.1.4 on 2023-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0004_remove_seedrequest_seed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Mint', 'Mint'), ('Chase', 'Chase'), ('Fidelity', 'Fidelity')], default='Chase', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='account_type',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Mint', 'Mint'), ('Chase', 'Chase'), ('Fidelity', 'Fidelity')], default='Chase', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Debit', max_length=100),
        ),
    ]
