# Generated by Django 4.1.4 on 2022-12-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0005_alter_category_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_identity', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
