# Generated by Django 4.1.4 on 2023-02-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0005_alter_account_name_alter_fileupload_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Mint', 'Mint'), ('Chase', 'Chase'), ('Fidelity', 'Fidelity')], default='Amazon', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='account_type',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Mint', 'Mint'), ('Chase', 'Chase'), ('Fidelity', 'Fidelity')], default='Amazon', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledgered_app.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=100),
        ),
    ]
