# Generated by Django 4.1.4 on 2022-12-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0006_seeded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeded',
            old_name='is_identity',
            new_name='seeded',
        ),
    ]
