# Generated by Django 4.1.4 on 2023-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0007_rename_is_identity_seeded_seeded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=2)),
                ('amount', models.FloatField()),
                ('account', models.CharField(max_length=200)),
                ('original_description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pretty_description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='account_type',
            field=models.CharField(choices=[('A', 'Amazon'), ('M', 'Mint'), ('C', 'Chase')], default='F', max_length=2),
        ),
    ]
