# Generated by Django 4.1.4 on 2023-02-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0007_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='predicate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
