# Generated by Django 4.1.4 on 2023-02-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0008_alter_description_predicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='is_identity',
        ),
    ]
