# the default categories that are given to every new account
categories:
- amusement & recreation
- debt payments
- bars & restaurants
- coffee shops
- delivery food
- grocery & corner store
- rent and utilities
- ignore
- income
- insurance
- lodging
- medical
- misc
- savings & invesment
- services
- shopping
- subscriptions & memberships
- taxes
- transportation
- travel