# Generated by Django 4.1.4 on 2023-02-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgered_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadsummary',
            old_name='ignored',
            new_name='duplicate',
        ),
    ]
